### ISSUE TITLE
Seed crash on medic creation

### ISSUE THREAD

**Issue by Crysicia** [JMD60260/llsolidaires#145]
**Description**
Seed crash when trying to create a medic.

**Error**
```ActiveRecord::RecordInvalid: Validation failed: Proof can't be blank, Identity file can't be blank```

**To Reproduce**
1. Empty your database
2. `rails db:seed`

**Expected behavior**
Should run fine, it's a seed yo!

**Full logs**
```
Commencement des seeds
 
Nettoyage de la base de données en cours ...
Toutes les locations ont été effacées
Tous les appartements ont été supprimés
Tous les users ont été supprimés
Tous les hopitaux ont été supprimés
Création de nouveaux utilisateurs
Création de Jean...(propriétaire)
Création de Pierre...(propriétaire)
Création de Julio...(propriétaire)
Création de Phill...(Medic)
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Proof can't be blank, Identity file can't be blank
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/validations.rb:81:in `raise_validation_error'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/validations.rb:53:in `save!'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:319:in `block in save!'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:319:in `save!'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/suppressor.rb:48:in `save!'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:55:in `create!'
/Volumes/Weathley/° Sorted up/Code/Work/JMD60160/llsolidaires/db/seeds.rb:52:in `<main>'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:556:in `block in load_seed'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:676:in `with_inline_jobs'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:556:in `load_seed'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Volumes/Weathley/° Sorted up/Code/Work/JMD60160/llsolidaires/bin/rails:9:in `<top (required)>'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/lucien/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Volumes/Weathley/° Sorted up/Code/Work/JMD60160/llsolidaires/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)```

**Comment by JMD60260** [comment]
Need to fix validation of identity file and proof upload when seed the DB
